trigger:
- main

pool:
  name: selfhostedforterraform

stages:
- stage: Initialize
  jobs:
  - job: TerraformInitializeJob
    steps:
    - script: |
        #!/bin/bash
        # Check if terraform is installed
        if ! [ -x "$(command -v terraform)" ]; then
          echo 'Terraform is not installed. Installing now...'
          sudo snap install terraform --classic
        else
          echo 'Terraform is already installed.'
        fi
        # Display terraform version
        terraform -v
      displayName: 'Install Terraform if not present'

    - script: terraform init
      displayName: 'terraform init'

- stage: Validate
  jobs:
  - job: TerraformValidateJob
    steps:
    - script: terraform validate
      displayName: 'terraform validate'
